# Generated by Django 6.1 on 2026-08-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='NIF',
            new_name='nif',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('ortopedista', 'Ortopedista'), ('cardiologista', 'Cardiologista'), ('neurologista', 'Neurologista')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('medico', 'Médico'), ('paciente', 'Paciente')], max_length=10),
        ),
    ]
