# Generated by Django 6.1 on 2026-09-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_nif_usuario_nif_alter_usuario_especialidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
